version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # Google
  
  GOOGLE_SERVICE_ACC_KEY_FILEPATH: "/home/src/google-cred.json"
  GOOGLE_LOCATION: US # Optional
