version: 2

models:
  - name: fact_movie_genres
    description: >
      Facts about each movie, including title, release year, genre
  - name: top_people_ratings
    description: >
      Returns the number of movies, average rating of movies, and the average number of votes a director/performer receives for each year
  - name: top_movie_ratings
    description: >
      Returns top 20 movies for each year based on the average rating and number of votes